<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>ilyvion.LaboratoryMod</RootNamespace>
        <AssemblyName>ilyvion.LaboratoryMod</AssemblyName>
        <NoWarn>CA1310;CA1307</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ilyvion.Laboratory\ilyvion.Laboratory.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Publicize Include="Assembly-CSharp:Verse.XmlInheritance.GetBestParentFor" />
        <Publicize Include="Assembly-CSharp:Verse.XmlInheritance+XmlInheritanceNode" />
        <Publicize Include="Assembly-CSharp:Verse.XmlInheritance.unresolvedNodes" />
    </ItemGroup>
</Project>
