name: Build

on:
    workflow_call:
        inputs:
            artifact-suffix:
                required: true
                type: string

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Build Mod for 1.5
              env:
                  RimWorldVersion: 1.5
              run: dotnet build --configuration Release ilyvion.Laboratory.sln

            - name: Build Mod for 1.4
              env:
                  RimWorldVersion: 1.4
              run: dotnet build --configuration Release ilyvion.Laboratory.sln

            - name: Build Mod for 1.3
              env:
                  RimWorldVersion: 1.3
              run: dotnet build --configuration Release ilyvion.Laboratory.sln

            - name: Upload Mod Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ilyvion.Laboratory-${{ inputs.artifact-suffix }}
                  path: |
                      About/
                      1.5/
                      1.4/
                      1.3/
                      Common/
                      LICENSE
                      LICENSE.Apache-2.0
                      LICENSE.MIT
                      README.md
                      CHANGELOG.md
                      LoadFolders.xml
                      !**/.*
                      !About/*.pdn
                      !About/*.svg
                      !About/*.ttf
